### PR TITLE
fix(snap): remove '-go' suffix from service name and update epoch

### PR DESCRIPTION
**Pull request by siggiskulason**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/device-camera-go/blob/master/.github/CONTRIBUTING.md

## What is the current behavior?

The snap currently doesn't build and install correctly, as it still expects the application to install to be
`./cmd/device-camera-go` and it's been renamed in the Makefile to `./cmd/device-camera`

## What is the new behavior?

- The service name is now device-camera, not device-camera-go. Starting the device is therefore now done with
 `sudo snap start edgex-device-camera.device-camera`

- The snap path has also changed accordingly
from `/var/snap/edgex-device-camera/current/config/device-camera-go/` to `/var/snap/edgex-device-camera/current/config/device-camera/`
- The epoch value has been updated and version name set to "Ireland"

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

BREAKING CHANGE: The epoch has been updated for Ireland.
BREAKING CHANGE: The snap service name and path has changed to device-camera

## New Imports

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by lenny-intel — DISMISSED** [review]
LGTM

**Review by tonyespy — APPROVED** [review]
LGTM

**Comment by siggiskulason** [comment]
Just force-pushed a change as suggested by @tonyespy - epoch should be 4, not 5, as we didn't update the epoch for hanoi

**Review by tonyespy — APPROVED** [review]
one more time....

**Review by lenny-intel — APPROVED** [review]

**Pull request merged**
