### PR TITLE
fix: check for nil before adding an onvifClient

### PR DESCRIPTION
**Pull request by siggiskulason**
If a device is not reachable, then device-camera will now try to reconnect and set it up on every autoevent,
rather than crashing with a nil pointer dereference.

Signed-off-by: Siggi Skulason <siggi.skulason@canonical.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://wiki.edgexfoundry.org/display/FA/Contributor%27s+Guide
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?
1. Define a camera device and an associated autoevent
2. Unplug the camera
3. Start up device-camera
4. Device-camera logs an error when starting up, but still adds the device to the onvifClients map, with a nil pointer. Then when the AutoEvent runs, it will dereference that nil pointer and crash with a segmentation fault.

Issue Number: [47](https://github.com/edgexfoundry/device-camera-go/issues/47) 

## What is the new behavior?
1. If the camera is not reachable when the device starts up, then it is not added to the onvifClients map, so no nil reference is stored.
2. During the AutoEvent, as there is no reference to the camera, the driver will try again to connect. 
3. If it fails, then an error is logged each time
4. If it succeeds, then a reference is stored in onvifClients and the camera can then be used.
5. If the camera is unplugged again, then errors are generated until the camera is plugged back in.

So device-camera does not crash anymore if the a device is offline.

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Are there any new imports or modules? If so, what are they used for and why?
No

## Are there any specific instructions or things that should be known prior to reviewing?
No
## Other information

### CODE REVIEW

**Review by tonyespy — CHANGES_REQUESTED** [review]
Your fix looks good.

That said, can you please revise your commit message? In general, your commit summary should indicate what you've changed, not what you're fixing.

So something like:

`fix: check for nil before adding an onvifClient
`

Also, I'm not sure why people started adding (#xxxx) to the end of their commit summaries, especially when the numbers don't actually match the issue being fixed (although yours does).

In general, to make github auto-close an issue, you should add a separate line after the commit summary that uses: fix/fixes/fixed, close/closes/closed, ...  Like this:

`fixes: #47 
`

For reference, here's a [description](https://docs.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords) of how this works for github.

**Comment by siggiskulason** [comment]
Thanks, @tonyespy - I've updated the commit message and summary - and this PR title to match.

**Review by tonyespy — APPROVED** [review]
Thanks for the changes, LGTM!

**Review by cloudxxx8 — APPROVED** [review]
LGTM

**Pull request merged**
