### PR TITLE
Update SDK version, add attribution-test and missing attributions

### LINKED ISSUE #23: Update SDK to latest version
update device-sdk-go to v1.1.1

### PR DESCRIPTION
**Pull request by hahattan**
Update device-sdk-go to latest (v1.1.1) version, add test-attribution in `Makefile` and update missing attributions

Fix #23

### CODE REVIEW

**Comment by lranjbar** [comment]
@hahattan  This CI build for this repository has been updated. You will need to rebase off the master branch to rebuild.

**Comment by hahattan** [comment]
rebased, also add the go-mod-tidy test script and update go.mod

**Comment by hahattan** [comment]
@cloudxxx8

**Comment by cloudxxx8** [comment]
update SDK version to v1.1.2

**Pull request merged**
